// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionAccount = `-- name: GetSessionAccount :one
SELECT id, display_name FROM accounts WHERE id = $1 AND rp_id = $2
`

type GetSessionAccountParams struct {
	ID   pgtype.UUID
	RpID string
}

type GetSessionAccountRow struct {
	ID          pgtype.UUID
	DisplayName string
}

func (q *Queries) GetSessionAccount(ctx context.Context, arg GetSessionAccountParams) (GetSessionAccountRow, error) {
	row := q.db.QueryRow(ctx, getSessionAccount, arg.ID, arg.RpID)
	var i GetSessionAccountRow
	err := row.Scan(&i.ID, &i.DisplayName)
	return i, err
}
