// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, display_name, rp_id, webauthn_user_handle)
VALUES ($1, $2, $3, $4)
`

type CreateAccountParams struct {
	ID                 pgtype.UUID
	DisplayName        string
	RpID               string
	WebauthnUserHandle []byte
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.DisplayName,
		arg.RpID,
		arg.WebauthnUserHandle,
	)
	return err
}

const createPasskeyCredential = `-- name: CreatePasskeyCredential :exec
INSERT INTO passkey_credentials (
    account_id, rp_id, credential_id, public_key, attestation_type,
    attestation_format, transports, flags, aaguid, sign_count,
    clone_warning, attachment, attestation, extensions
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreatePasskeyCredentialParams struct {
	AccountID         pgtype.UUID
	RpID              string
	CredentialID      []byte
	PublicKey         []byte
	AttestationType   string
	AttestationFormat string
	Transports        []string
	Flags             int16
	Aaguid            []byte
	SignCount         int64
	CloneWarning      bool
	Attachment        string
	Attestation       []byte
	Extensions        []byte
}

func (q *Queries) CreatePasskeyCredential(ctx context.Context, arg CreatePasskeyCredentialParams) error {
	_, err := q.db.Exec(ctx, createPasskeyCredential,
		arg.AccountID,
		arg.RpID,
		arg.CredentialID,
		arg.PublicKey,
		arg.AttestationType,
		arg.AttestationFormat,
		arg.Transports,
		arg.Flags,
		arg.Aaguid,
		arg.SignCount,
		arg.CloneWarning,
		arg.Attachment,
		arg.Attestation,
		arg.Extensions,
	)
	return err
}
