// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connection.sql

package queries

import (
	"context"
)

const checkConnection = `-- name: CheckConnection :one
SELECT 1
`

func (q *Queries) CheckConnection(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkConnection)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
