// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connection_audit.sql

package queries

import (
	"context"
	"database/sql"
)

const insertConnectionAuditEvent = `-- name: InsertConnectionAuditEvent :exec
INSERT INTO connection_audit_events (
    id, account_id, saved_connection_id, attempt_id, connection_name,
    host, port, username, event_type, failure_code, occurred_at, jump_snapshot, failure_hop
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertConnectionAuditEventParams struct {
	ID                string
	AccountID         string
	SavedConnectionID string
	AttemptID         string
	ConnectionName    string
	Host              string
	Port              int64
	Username          string
	EventType         string
	FailureCode       sql.NullString
	OccurredAt        int64
	JumpSnapshot      sql.NullString
	FailureHop        sql.NullString
}

func (q *Queries) InsertConnectionAuditEvent(ctx context.Context, arg InsertConnectionAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertConnectionAuditEvent,
		arg.ID,
		arg.AccountID,
		arg.SavedConnectionID,
		arg.AttemptID,
		arg.ConnectionName,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.EventType,
		arg.FailureCode,
		arg.OccurredAt,
		arg.JumpSnapshot,
		arg.FailureHop,
	)
	return err
}
