// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: host_trust.sql

package queries

import (
	"context"
)

const approveHostTrust = `-- name: ApproveHostTrust :exec
INSERT INTO host_trust (account_id, host, port, public_key, trusted_at)
VALUES (?, ?, ?, ?, ?) ON CONFLICT (account_id, host, port) DO NOTHING
`

type ApproveHostTrustParams struct {
	AccountID string
	Host      string
	Port      int64
	PublicKey []byte
	TrustedAt int64
}

func (q *Queries) ApproveHostTrust(ctx context.Context, arg ApproveHostTrustParams) error {
	_, err := q.db.ExecContext(ctx, approveHostTrust,
		arg.AccountID,
		arg.Host,
		arg.Port,
		arg.PublicKey,
		arg.TrustedAt,
	)
	return err
}

const getHostTrust = `-- name: GetHostTrust :one
SELECT account_id, host, port, public_key, trusted_at FROM host_trust WHERE account_id = ? AND host = ? AND port = ?
`

type GetHostTrustParams struct {
	AccountID string
	Host      string
	Port      int64
}

func (q *Queries) GetHostTrust(ctx context.Context, arg GetHostTrustParams) (HostTrust, error) {
	row := q.db.QueryRowContext(ctx, getHostTrust, arg.AccountID, arg.Host, arg.Port)
	var i HostTrust
	err := row.Scan(
		&i.AccountID,
		&i.Host,
		&i.Port,
		&i.PublicKey,
		&i.TrustedAt,
	)
	return i, err
}

const getOwnedConnection = `-- name: GetOwnedConnection :one
SELECT id, account_id, name, host, port, username, ssh_key_id, created_at, updated_at FROM saved_connections WHERE id = ? AND account_id = ?
`

type GetOwnedConnectionParams struct {
	ID        string
	AccountID string
}

func (q *Queries) GetOwnedConnection(ctx context.Context, arg GetOwnedConnectionParams) (SavedConnection, error) {
	row := q.db.QueryRowContext(ctx, getOwnedConnection, arg.ID, arg.AccountID)
	var i SavedConnection
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.SshKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedEncryptedSSHKey = `-- name: GetOwnedEncryptedSSHKey :one
SELECT encrypted_private_key FROM ssh_keys WHERE id = ? AND account_id = ?
`

type GetOwnedEncryptedSSHKeyParams struct {
	ID        string
	AccountID string
}

func (q *Queries) GetOwnedEncryptedSSHKey(ctx context.Context, arg GetOwnedEncryptedSSHKeyParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getOwnedEncryptedSSHKey, arg.ID, arg.AccountID)
	var encrypted_private_key []byte
	err := row.Scan(&encrypted_private_key)
	return encrypted_private_key, err
}

const resetHostTrust = `-- name: ResetHostTrust :execrows
DELETE FROM host_trust WHERE account_id = ? AND host = ? AND port = ? AND public_key = ?
`

type ResetHostTrustParams struct {
	AccountID string
	Host      string
	Port      int64
	PublicKey []byte
}

func (q *Queries) ResetHostTrust(ctx context.Context, arg ResetHostTrustParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetHostTrust,
		arg.AccountID,
		arg.Host,
		arg.Port,
		arg.PublicKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
