// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: key_encryption.sql

package queries

import (
	"context"
)

const listEncryptedSSHKeys = `-- name: ListEncryptedSSHKeys :many
SELECT id, account_id, encrypted_private_key FROM ssh_keys
`

type ListEncryptedSSHKeysRow struct {
	ID                  string
	AccountID           string
	EncryptedPrivateKey []byte
}

func (q *Queries) ListEncryptedSSHKeys(ctx context.Context) ([]ListEncryptedSSHKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listEncryptedSSHKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncryptedSSHKeysRow
	for rows.Next() {
		var i ListEncryptedSSHKeysRow
		if err := rows.Scan(&i.ID, &i.AccountID, &i.EncryptedPrivateKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
