// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login.sql

package queries

import (
	"context"
	"database/sql"
)

const getLoginCredential = `-- name: GetLoginCredential :one
SELECT accounts.id, accounts.display_name, accounts.rp_id, accounts.webauthn_user_handle, accounts.created_at, passkey_credentials.account_id, passkey_credentials.rp_id, passkey_credentials.credential_id, passkey_credentials.public_key, passkey_credentials.attestation_type, passkey_credentials.attestation_format, passkey_credentials.transports, passkey_credentials.flags, passkey_credentials.aaguid, passkey_credentials.sign_count, passkey_credentials.clone_warning, passkey_credentials.attachment, passkey_credentials.attestation, passkey_credentials.extensions, passkey_credentials.created_at, passkey_credentials.last_used_at
FROM accounts
JOIN passkey_credentials ON passkey_credentials.account_id = accounts.id AND passkey_credentials.rp_id = accounts.rp_id
WHERE accounts.rp_id = ? AND passkey_credentials.credential_id = ? AND accounts.webauthn_user_handle = ?
`

type GetLoginCredentialParams struct {
	RpID               string
	CredentialID       []byte
	WebauthnUserHandle []byte
}

type GetLoginCredentialRow struct {
	Account           Account
	PasskeyCredential PasskeyCredential
}

func (q *Queries) GetLoginCredential(ctx context.Context, arg GetLoginCredentialParams) (GetLoginCredentialRow, error) {
	row := q.db.QueryRowContext(ctx, getLoginCredential, arg.RpID, arg.CredentialID, arg.WebauthnUserHandle)
	var i GetLoginCredentialRow
	err := row.Scan(
		&i.Account.ID,
		&i.Account.DisplayName,
		&i.Account.RpID,
		&i.Account.WebauthnUserHandle,
		&i.Account.CreatedAt,
		&i.PasskeyCredential.AccountID,
		&i.PasskeyCredential.RpID,
		&i.PasskeyCredential.CredentialID,
		&i.PasskeyCredential.PublicKey,
		&i.PasskeyCredential.AttestationType,
		&i.PasskeyCredential.AttestationFormat,
		&i.PasskeyCredential.Transports,
		&i.PasskeyCredential.Flags,
		&i.PasskeyCredential.Aaguid,
		&i.PasskeyCredential.SignCount,
		&i.PasskeyCredential.CloneWarning,
		&i.PasskeyCredential.Attachment,
		&i.PasskeyCredential.Attestation,
		&i.PasskeyCredential.Extensions,
		&i.PasskeyCredential.CreatedAt,
		&i.PasskeyCredential.LastUsedAt,
	)
	return i, err
}

const updateLoginCredential = `-- name: UpdateLoginCredential :exec
UPDATE passkey_credentials
SET sign_count = ?, clone_warning = ?, flags = ?, last_used_at = ?
WHERE account_id = ? AND rp_id = ?
`

type UpdateLoginCredentialParams struct {
	SignCount    int64
	CloneWarning int64
	Flags        int64
	LastUsedAt   sql.NullInt64
	AccountID    string
	RpID         string
}

func (q *Queries) UpdateLoginCredential(ctx context.Context, arg UpdateLoginCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateLoginCredential,
		arg.SignCount,
		arg.CloneWarning,
		arg.Flags,
		arg.LastUsedAt,
		arg.AccountID,
		arg.RpID,
	)
	return err
}
