// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
)

type Account struct {
	ID                 string
	DisplayName        string
	RpID               string
	WebauthnUserHandle []byte
	CreatedAt          int64
}

type PasskeyCredential struct {
	AccountID         string
	RpID              string
	CredentialID      []byte
	PublicKey         []byte
	AttestationType   string
	AttestationFormat string
	Transports        string
	Flags             int64
	Aaguid            []byte
	SignCount         int64
	CloneWarning      int64
	Attachment        string
	Attestation       string
	Extensions        string
	CreatedAt         int64
	LastUsedAt        sql.NullInt64
}

type Session struct {
	Token  string
	Data   []byte
	Expiry int64
}

type SshKey struct {
	ID                  string
	AccountID           string
	Name                string
	PublicFingerprint   string
	EncryptedPrivateKey []byte
	CreatedAt           int64
}
