// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package queries

import (
	"context"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, display_name, rp_id, webauthn_user_handle, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateAccountParams struct {
	ID                 string
	DisplayName        string
	RpID               string
	WebauthnUserHandle []byte
	CreatedAt          int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.DisplayName,
		arg.RpID,
		arg.WebauthnUserHandle,
		arg.CreatedAt,
	)
	return err
}

const createPasskeyCredential = `-- name: CreatePasskeyCredential :exec
INSERT INTO passkey_credentials (
    account_id, rp_id, credential_id, public_key, attestation_type,
    attestation_format, transports, flags, aaguid, sign_count,
    clone_warning, attachment, attestation, extensions, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePasskeyCredentialParams struct {
	AccountID         string
	RpID              string
	CredentialID      []byte
	PublicKey         []byte
	AttestationType   string
	AttestationFormat string
	Transports        string
	Flags             int64
	Aaguid            []byte
	SignCount         int64
	CloneWarning      int64
	Attachment        string
	Attestation       string
	Extensions        string
	CreatedAt         int64
}

func (q *Queries) CreatePasskeyCredential(ctx context.Context, arg CreatePasskeyCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createPasskeyCredential,
		arg.AccountID,
		arg.RpID,
		arg.CredentialID,
		arg.PublicKey,
		arg.AttestationType,
		arg.AttestationFormat,
		arg.Transports,
		arg.Flags,
		arg.Aaguid,
		arg.SignCount,
		arg.CloneWarning,
		arg.Attachment,
		arg.Attestation,
		arg.Extensions,
		arg.CreatedAt,
	)
	return err
}
