// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_connections.sql

package queries

import (
	"context"
	"database/sql"
)

const createSavedConnection = `-- name: CreateSavedConnection :one
INSERT INTO saved_connections (id, account_id, name, host, port, username, ssh_key_id, created_at, updated_at, jump_connection_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, account_id, name, host, port, username, ssh_key_id, created_at, updated_at, jump_connection_id
`

type CreateSavedConnectionParams struct {
	ID               string
	AccountID        string
	Name             string
	Host             string
	Port             int64
	Username         string
	SshKeyID         string
	CreatedAt        int64
	UpdatedAt        int64
	JumpConnectionID sql.NullString
}

func (q *Queries) CreateSavedConnection(ctx context.Context, arg CreateSavedConnectionParams) (SavedConnection, error) {
	row := q.db.QueryRowContext(ctx, createSavedConnection,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.SshKeyID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.JumpConnectionID,
	)
	var i SavedConnection
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.SshKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JumpConnectionID,
	)
	return i, err
}

const deleteSavedConnection = `-- name: DeleteSavedConnection :execrows
DELETE FROM saved_connections WHERE id = ? AND account_id = ?
`

type DeleteSavedConnectionParams struct {
	ID        string
	AccountID string
}

func (q *Queries) DeleteSavedConnection(ctx context.Context, arg DeleteSavedConnectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSavedConnection, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listSavedConnections = `-- name: ListSavedConnections :many
SELECT id, account_id, name, host, port, username, ssh_key_id, created_at, updated_at, jump_connection_id FROM saved_connections WHERE account_id = ? ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListSavedConnections(ctx context.Context, accountID string) ([]SavedConnection, error) {
	rows, err := q.db.QueryContext(ctx, listSavedConnections, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedConnection
	for rows.Next() {
		var i SavedConnection
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.SshKeyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JumpConnectionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavedConnection = `-- name: UpdateSavedConnection :one
UPDATE saved_connections SET name = ?1, host = ?2, port = ?3, username = ?4, ssh_key_id = ?5, jump_connection_id = ?6, updated_at = max(updated_at, CAST(?7 AS INTEGER))
WHERE id = ?8 AND account_id = ?9 RETURNING id, account_id, name, host, port, username, ssh_key_id, created_at, updated_at, jump_connection_id
`

type UpdateSavedConnectionParams struct {
	Name             string
	Host             string
	Port             int64
	Username         string
	SshKeyID         string
	JumpConnectionID sql.NullString
	UpdatedAt        int64
	ID               string
	AccountID        string
}

func (q *Queries) UpdateSavedConnection(ctx context.Context, arg UpdateSavedConnectionParams) (SavedConnection, error) {
	row := q.db.QueryRowContext(ctx, updateSavedConnection,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.SshKeyID,
		arg.JumpConnectionID,
		arg.UpdatedAt,
		arg.ID,
		arg.AccountID,
	)
	var i SavedConnection
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.SshKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JumpConnectionID,
	)
	return i, err
}
