// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ssh_keys.sql

package queries

import (
	"context"
)

const createSSHKey = `-- name: CreateSSHKey :exec
INSERT INTO ssh_keys (id, account_id, name, public_fingerprint, encrypted_private_key, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSSHKeyParams struct {
	ID                  string
	AccountID           string
	Name                string
	PublicFingerprint   string
	EncryptedPrivateKey []byte
	CreatedAt           int64
}

func (q *Queries) CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) error {
	_, err := q.db.ExecContext(ctx, createSSHKey,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.PublicFingerprint,
		arg.EncryptedPrivateKey,
		arg.CreatedAt,
	)
	return err
}

const deleteSSHKey = `-- name: DeleteSSHKey :execrows
DELETE FROM ssh_keys WHERE id = ? AND account_id = ?
`

type DeleteSSHKeyParams struct {
	ID        string
	AccountID string
}

func (q *Queries) DeleteSSHKey(ctx context.Context, arg DeleteSSHKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSSHKey, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listSSHKeyMetadata = `-- name: ListSSHKeyMetadata :many
SELECT id, name, public_fingerprint, created_at FROM ssh_keys
WHERE account_id = ? ORDER BY created_at DESC, id ASC
`

type ListSSHKeyMetadataRow struct {
	ID                string
	Name              string
	PublicFingerprint string
	CreatedAt         int64
}

func (q *Queries) ListSSHKeyMetadata(ctx context.Context, accountID string) ([]ListSSHKeyMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, listSSHKeyMetadata, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSSHKeyMetadataRow
	for rows.Next() {
		var i ListSSHKeyMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicFingerprint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
