/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthedConnectionsIndexRouteImport } from './routes/_authed/connections/index'
import { Route as AuthedKeysIndexRouteImport } from './routes/_authed/keys/index'
import { Route as AuthedWorkspaceIndexRouteImport } from './routes/_authed/workspace/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedConnectionsIndexRoute = AuthedConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedKeysIndexRoute = AuthedKeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedWorkspaceIndexRoute = AuthedWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/connections/': typeof AuthedConnectionsIndexRoute
  '/keys/': typeof AuthedKeysIndexRoute
  '/workspace/': typeof AuthedWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/connections': typeof AuthedConnectionsIndexRoute
  '/keys': typeof AuthedKeysIndexRoute
  '/workspace': typeof AuthedWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authed/connections/': typeof AuthedConnectionsIndexRoute
  '/_authed/keys/': typeof AuthedKeysIndexRoute
  '/_authed/workspace/': typeof AuthedWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/' | '/connections/' | '/keys/' | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/connections' | '/keys' | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login/'
    | '/_authed/connections/'
    | '/_authed/keys/'
    | '/_authed/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/connections/': {
      id: '/_authed/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AuthedConnectionsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/keys/': {
      id: '/_authed/keys/'
      path: '/keys'
      fullPath: '/keys/'
      preLoaderRoute: typeof AuthedKeysIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/workspace/': {
      id: '/_authed/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthedWorkspaceIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedConnectionsIndexRoute: typeof AuthedConnectionsIndexRoute
  AuthedKeysIndexRoute: typeof AuthedKeysIndexRoute
  AuthedWorkspaceIndexRoute: typeof AuthedWorkspaceIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedConnectionsIndexRoute: AuthedConnectionsIndexRoute,
  AuthedKeysIndexRoute: AuthedKeysIndexRoute,
  AuthedWorkspaceIndexRoute: AuthedWorkspaceIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
